/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MarrySign } from "./MarrySign";
export * as factories from "./factories";
export { MarrySign__factory } from "./factories/MarrySign__factory";
